### ISSUE TITLE
[0.25] Weather data is not synced

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/AsteroidOSSync#179] opened 2022-11-09 11:27 UTC
I could test on android 12 (Lineage 19.1) and was not able to sync weather data using 0.25.

Note,
Successfully adding the watch (tunny) to AOSSync only worked after i completely removed the app and rebooted.
When just updating from 0.24, (and wiping data/cache) the app would claim connection but did not actually trigger pairing.

**Comment by jrtberlin** [comment] 2022-11-09 19:47
Duplicate of #175

**Closed** 2022-11-09 23:07 UTC
Labels: duplicate
