### ISSUE TITLE
Crash on tapping notification

### ISSUE THREAD

**Issue by TheLastProject** [AsteroidOS/AsteroidOSSync#4] opened 2016-12-17 15:02 UTC
Phone: Motorola Moto E 2015 LTE
Phone OS: CyanogenMod 14.1-20161216-NIGHTLY-surnia (Android 7.1.1)
Watch: LG G Watch (dory) running the official AsteroidOS alpha 1.0 build

I see the following crash when I tap the notification (which often still says "Connected to dory"):
```
12-17 15:58:56.670 11527 11527 E AndroidRuntime: FATAL EXCEPTION: main
12-17 15:58:56.670 11527 11527 E AndroidRuntime: Process: org.asteroidos.sync, PID: 11527
12-17 15:58:56.670 11527 11527 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toUpperCase()' on a null object r
eference
12-17 15:58:56.670 11527 11527 E AndroidRuntime:        at com.idevicesinc.sweetblue.utils.Utils_String.normalizeMacAddress(Utils_String.java:37)
12-17 15:58:56.670 11527 11527 E AndroidRuntime:        at com.idevicesinc.sweetblue.BleManager.normalizeMacAddress(BleManager.java:3362)
12-17 15:58:56.670 11527 11527 E AndroidRuntime:        at com.idevicesinc.sweetblue.BleManager.getDevice(BleManager.java:2235)
12-17 15:58:56.670 11527 11527 E AndroidRuntime:        at org.asteroidos.sync.services.SynchronizationService$SynchronizationHandler.handleMessage(SynchronizationService.java:78)
12-17 15:58:56.670 11527 11527 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
12-17 15:58:56.670 11527 11527 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-17 15:58:56.670 11527 11527 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6126)
12-17 15:58:56.670 11527 11527 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-17 15:58:56.670 11527 11527 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
12-17 15:58:56.670 11527 11527 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
12-17 15:58:56.693  1073  6207 W ActivityManager:   Force finishing activity org.asteroidos.sync/.DeviceDetailActivity
12-17 15:58:56.702  1073  6207 W ActivityManager:   Force finishing activity org.asteroidos.sync/.DeviceDetailActivity
```

This never seemed to happen on me on Android 6, it may have to do with bugs in the new CyanogenMod 14.1 nightlies, but most other apps remain stable.

**Comment by KorakSilvercloud** [comment] 2016-12-31 02:48
I was seeing the app crash any time I tapped the notification, even if I had just connected. This was the same thing I was seeing in my logs. I think we might have the crash issue figured out. The missing notifications though will probably be something else to chase down.

**Comment by TheLastProject** [comment] 2017-01-03 12:30
Oh you're right, this is actually caused by tapping the notification. The missing notifications is a different issue. Thanks for the note

**Comment by FlorentRevest** [comment] 2017-03-29 20:00
I can't reproduce the bug anymore since the activities handling rewrite of https://github.com/AsteroidOS/AsteroidOSSync/commit/df34c985970d6ef295c72a2c48ce7ebc815c1aa3 I close the issue.

**Closed by FlorentRevest** 2017-03-29 20:00 UTC
